replicas: 1

int_app_name: internal-nginx
ext_app_name: external-nginx

external_image_name: docker.io/alpine
internal_image_name: internal-alpine
internal_image_tag: int

with_deploy: false
with_validate_source: false
with_validate_targe: false

default_registry: "{{ 'docker-registry.default.svc:5000' if cluster_version is version('4.1', '<') else 'image-registry.openshift-image-registry.svc:5000' }}"
