namespace: ocp-24995-role
rolebinding_name: basic-role-binding
rolename: basic-role

with_deploy: false
with_validate_source: false
with_validate_target: false

apis:
  role:
    default: "rbac.authorization.k8s.io/v1beta1"
    "3.7": "v1"
  rolebinding:
    default: "rbac.authorization.k8s.io/v1beta1"
    "3.7": "v1"

role_api: "{{ apis.role.get(cluster_version, apis.role.get('default')) }}"
rolebinding_api: "{{ apis.rolebinding.get(cluster_version, apis.rolebinding.get('default')) }}"
