- name: Create resources
  import_tasks: deploy.yml
  when: with_deploy|bool

- name: Validate source
  import_tasks: validate-source.yml
  when: with_validate_source|bool

- name: Validate migration
  import_tasks: validate-target.yml
  when: with_validate_target|bool
