- name: Create namespace for {{ namespace }}
  shell: "{{ oc_binary }} new-project {{ namespace }} --server {{ url }} --token {{ token }} --skip-config-write=true"

- name: Deploy Role and RoleBinding
  k8s:
    host: "{{ url }}"
    api_key: "{{ token }}"
    verify_ssl: no
    state : present
    namespace : "{{ namespace }}"
    definition: "{{ lookup('template', 'basic-sa-role-template.yml.j2' )}}"
